### ISSUE TITLE
How to revert?

### ISSUE THREAD

**Issue by puppinoo** [lorenz/asrock-x300-s3-fix#7]
Hi,
I followed the README instructions and I was able to enable S3 state. I didn't fully understand the # 2 of the WARNINGS section.
What can't I do now? I can't go into bios panel and modify anything?
What if I need to do that? How can I fully revert to go back to original working?

Thanks for this great solution.
Pino.

**Comment by lorenz** [comment]
The problem is that the firmware (UEFI/BIOS) passes data about the system configuration via ACPI tables. This hack overrides a specific (but important) ACPI table with a patched version which is not actually sourced from the firmware, but baked into the initramfs. This means that if the firmware updates the ACPI table it passes to the OS that change doesn't actually make it to the OS as it uses that baked-in table. By undoing the patch (by removing the cpio from the initrd), making changes and then regenerating the cpio you pick up any changes the firmware made as a result of you changing settings.

Not all settings affect the DSDT table (which this patches), but exhaustively enumerating all which do is rather tedious and hasn't been done.

Note that you don't need to revert anything on the firmware side, as this patch is loaded by Linux on every boot, so by just excluding it from the initrd you're back to the stock behavior.
